export default function Privacy(){return <main><header><h1>Política de Privacidade</h1><p className="muted">SOL SERVICOS DE OFTALMOLOGIA LTDA — CNPJ 00.898.428/0008-70</p><p className="muted">Última atualização: 18 de setembro de 2026</p></header>
<h2>1. Quem somos</h2><p>A SOL SERVICOS DE OFTALMOLOGIA LTDA, CNPJ 00.898.428/0008-70, com endereço na Avenida Aracaju, 1682, São Pedro, Ji-Paraná/RO, CEP 76913-602, realiza serviços de saúde e oftalmologia e é responsável pelo tratamento de dados pessoais nos contextos em que atua como controladora, observadas as responsabilidades definidas com terceiros.</p>
<h2>2. Dados que podem ser tratados</h2><p>Conforme o serviço utilizado, podemos tratar dados de identificação e contato, dados de agendamento e atendimento, informações administrativas e de cobrança, além de dados relacionados à saúde, exames, diagnósticos, procedimentos e documentos enviados pelo paciente quando necessários à prestação dos serviços.</p>
<h2>3. Dados de saúde</h2><p>Informações de saúde são dados pessoais sensíveis. Seu tratamento ocorre somente para finalidades legítimas relacionadas à prestação de serviços de saúde, atendimento, cumprimento de obrigações legais ou exercício regular de direitos, observada a legislação aplicável.</p>
<h2>4. Finalidades</h2><p>Os dados podem ser utilizados para realizar e organizar atendimentos, agendamentos, comunicações sobre serviços, execução de procedimentos, emissão de documentos e cobranças, relacionamento com pacientes, cumprimento de obrigações legais e regulatórias, segurança e prevenção de fraudes.</p>
<h2>5. WhatsApp e canais digitais</h2><p>Quando o paciente utiliza canais digitais, como WhatsApp, os dados e mensagens fornecidos podem ser tratados para responder solicitações, organizar atendimentos e executar serviços solicitados. Também podem existir tratamentos realizados pelos próprios provedores das plataformas, de acordo com seus respectivos termos e políticas.</p>
<h2>6. Compartilhamento</h2><p>Quando necessário, os dados poderão ser compartilhados com profissionais e prestadores envolvidos no atendimento, laboratórios, operadoras ou parceiros relacionados ao serviço, fornecedores de tecnologia, sistemas de comunicação, contabilidade e autoridades públicas quando houver obrigação legal ou fundamento legítimo.</p>
<h2>7. Segurança</h2><p>Adotamos medidas técnicas e administrativas razoáveis para proteger os dados contra acessos não autorizados, perda, alteração ou divulgação indevida. Nenhum ambiente digital é absolutamente imune a riscos.</p>
<h2>8. Retenção</h2><p>Os dados são mantidos pelo período necessário às finalidades do tratamento e aos prazos legais, regulatórios e de exercício de direitos aplicáveis a serviços de saúde.</p>
<h2>9. Direitos do titular</h2><p>Nos termos da legislação aplicável, o titular pode solicitar informações sobre o tratamento de seus dados e exercer direitos previstos na LGPD, observadas as hipóteses legais que permitam ou exijam a conservação de determinados registros.</p>
<h2>10. Cookies e tecnologias</h2><p>Este site institucional pode utilizar recursos técnicos necessários ao seu funcionamento. Caso sejam utilizados cookies não essenciais ou ferramentas de análise, suas informações e respectivas finalidades deverão ser apresentadas de forma adequada ao usuário.</p>
<h2>11. Transferência internacional</h2><p>Alguns fornecedores de tecnologia e comunicação podem processar dados fora do Brasil. Quando aplicável, serão observadas as regras legais pertinentes às transferências internacionais de dados.</p>
<h2>12. Contato sobre privacidade</h2><p>Para solicitações relacionadas à privacidade e proteção de dados, o titular poderá utilizar os canais de contato oficiais da SOL Serviços de Oftalmologia. Os dados de contato específicos poderão ser disponibilizados pela empresa nos canais oficiais de atendimento.</p>
<h2>13. Atualizações</h2><p>Esta política poderá ser atualizada para refletir mudanças legais, operacionais ou tecnológicas. A versão vigente será disponibilizada nesta página.</p>
<footer>Esta página é um documento informativo e institucional. A aplicação da LGPD depende das circunstâncias concretas de cada tratamento de dados.</footer>
</main>}